import {
  Donation,
  DonationImpact,
  VolunteerOpportunity,
  VolunteerRecord,
  VolunteerProfile,
  BeneficiaryApplication,
  DashboardStats,
  AppNotification,
  User,
} from '../types';

export const mockUser: User = {
  id: 'u1',
  name: 'أحمد محمد',
  email: 'ahmed@example.com',
  phone: '01012345678',
  role: 'donor',
  createdAt: '2024-01-15',
  language: 'ar',
};

export const mockAdminUser: User = {
  id: 'admin1',
  name: 'مدير النظام',
  email: 'admin@charity.org',
  phone: '01000000000',
  role: 'admin',
  createdAt: '2023-01-01',
  language: 'ar',
};

export const mockDonations: Donation[] = [
  {
    id: 'd1',
    donorId: 'u1',
    amount: 500,
    currency: 'EGP',
    category: 'zakat',
    paymentMethod: 'vodafone_cash',
    status: 'completed',
    transactionRef: 'TXN-001',
    createdAt: '2024-12-01',
  },
  {
    id: 'd2',
    donorId: 'u1',
    amount: 200,
    currency: 'EGP',
    category: 'food',
    paymentMethod: 'instapay',
    status: 'completed',
    transactionRef: 'TXN-002',
    createdAt: '2024-12-15',
  },
  {
    id: 'd3',
    donorId: 'u1',
    amount: 1000,
    currency: 'EGP',
    category: 'medical',
    paymentMethod: 'vodafone_cash',
    status: 'completed',
    transactionRef: 'TXN-003',
    createdAt: '2025-01-05',
  },
  {
    id: 'd4',
    donorId: 'u1',
    amount: 300,
    currency: 'EGP',
    category: 'education',
    paymentMethod: 'bank_transfer',
    status: 'pending',
    createdAt: '2025-01-20',
  },
];

export const mockImpact: DonationImpact = {
  donationId: 'all',
  familiesHelped: 12,
  mealsProvided: 85,
  studentsSupported: 3,
  medicalCasesHelped: 2,
  description: 'أموالك ساهمت في إطعام 85 عائلة ودعم 3 طلاب وعلاج حالتين طبيتين',
};

export const mockOpportunities: VolunteerOpportunity[] = [
  {
    id: 'v1',
    title: 'Food Distribution Drive',
    titleAr: 'حملة توزيع الطعام',
    description: 'Help distribute food packages to families in need in Maadi area',
    descriptionAr: 'المساعدة في توزيع عبوات الطعام للعائلات المحتاجة في منطقة المعادي',
    category: 'food',
    location: 'المعادي، القاهرة',
    date: '2025-02-15',
    startTime: '09:00',
    endTime: '14:00',
    maxVolunteers: 20,
    currentVolunteers: 12,
    pointsReward: 50,
    status: 'open',
    skills: ['driving', 'physical_fitness'],
  },
  {
    id: 'v2',
    title: 'Education Support Program',
    titleAr: 'برنامج الدعم التعليمي',
    description: 'Teach children in underprivileged areas basic math and reading',
    descriptionAr: 'تعليم الأطفال في المناطق المحرومة أساسيات الرياضيات والقراءة',
    category: 'education',
    location: 'بولاق، القاهرة',
    date: '2025-02-18',
    startTime: '10:00',
    endTime: '13:00',
    maxVolunteers: 10,
    currentVolunteers: 5,
    pointsReward: 40,
    status: 'open',
    skills: ['teaching', 'patience'],
  },
  {
    id: 'v3',
    title: 'Medical Camp Organization',
    titleAr: 'تنظيم قافلة طبية',
    description: 'Assist in organizing a free medical camp for underserved communities',
    descriptionAr: 'المساعدة في تنظيم قافلة طبية مجانية للمجتمعات المحرومة',
    category: 'medical',
    location: 'الفيوم',
    date: '2025-02-25',
    startTime: '08:00',
    endTime: '16:00',
    maxVolunteers: 30,
    currentVolunteers: 18,
    pointsReward: 80,
    status: 'open',
    skills: ['medical', 'organization'],
  },
  {
    id: 'v4',
    title: 'Orphan Care Visit',
    titleAr: 'زيارة رعاية الأيتام',
    description: 'Spend time with orphans, organize activities and provide emotional support',
    descriptionAr: 'قضاء وقت مع الأيتام وتنظيم أنشطة وتقديم الدعم النفسي',
    category: 'kafala',
    location: 'دار الأورمان، الجيزة',
    date: '2025-03-01',
    startTime: '10:00',
    endTime: '15:00',
    maxVolunteers: 15,
    currentVolunteers: 8,
    pointsReward: 60,
    status: 'open',
    skills: ['communication', 'creativity'],
  },
];

export const mockVolunteerRecords: VolunteerRecord[] = [
  {
    id: 'vr1',
    volunteerId: 'u1',
    opportunityId: 'v1',
    hoursLogged: 5,
    pointsEarned: 50,
    status: 'accepted',
    checkedIn: true,
    checkInTime: '2025-01-15T09:00:00',
    checkOutTime: '2025-01-15T14:00:00',
    createdAt: '2025-01-10',
  },
  {
    id: 'vr2',
    volunteerId: 'u1',
    opportunityId: 'v2',
    hoursLogged: 3,
    pointsEarned: 40,
    status: 'accepted',
    checkedIn: true,
    checkInTime: '2025-01-20T10:00:00',
    checkOutTime: '2025-01-20T13:00:00',
    createdAt: '2025-01-18',
  },
];

export const mockVolunteerProfile: VolunteerProfile = {
  userId: 'u1',
  totalHours: 8,
  totalPoints: 90,
  badges: [
    {
      id: 'b1',
      name: 'First Step',
      nameAr: 'الخطوة الأولى',
      icon: '🌟',
      description: 'Completed first volunteer activity',
      earnedAt: '2025-01-15',
    },
  ],
  certificates: [],
  rank: 'Bronze',
};

export const mockBeneficiaryApplications: BeneficiaryApplication[] = [
  {
    id: 'ba1',
    applicantName: 'فاطمة حسن',
    nationalId: '29012345678901',
    phone: '01112345678',
    address: 'شارع 15، المعادي، القاهرة',
    familySize: 5,
    monthlyIncome: 2000,
    needCategory: 'food',
    description: 'أسرة مكونة من 5 أفراد، الأب متوفى، تحتاج لدعم غذائي شهري',
    documents: [],
    status: 'approved',
    createdAt: '2025-01-01',
    updatedAt: '2025-01-05',
  },
  {
    id: 'ba2',
    applicantName: 'محمد عبدالله',
    nationalId: '28512345678901',
    phone: '01212345678',
    address: 'شارع النيل، بولاق، القاهرة',
    familySize: 3,
    monthlyIncome: 1500,
    needCategory: 'medical',
    description: 'يحتاج لعملية قلب عاجلة، غير قادر على تحمل التكاليف',
    documents: [],
    status: 'pending',
    createdAt: '2025-01-15',
    updatedAt: '2025-01-15',
  },
  {
    id: 'ba3',
    applicantName: 'سارة أحمد',
    nationalId: '30012345678901',
    phone: '01512345678',
    address: 'مدينة نصر، القاهرة',
    familySize: 4,
    monthlyIncome: 3000,
    needCategory: 'education',
    description: 'طالبة جامعية متفوقة تحتاج لمنحة دراسية لإكمال دراستها',
    documents: [],
    status: 'under_review',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-22',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalDonations: 156,
  totalAmount: 285000,
  totalVolunteers: 45,
  totalBeneficiaries: 89,
  pendingApplications: 12,
  activeOpportunities: 4,
  monthlyTrend: [
    { month: 'Aug', amount: 15000 },
    { month: 'Sep', amount: 22000 },
    { month: 'Oct', amount: 18000 },
    { month: 'Nov', amount: 35000 },
    { month: 'Dec', amount: 55000 },
    { month: 'Jan', amount: 42000 },
  ],
  categoryBreakdown: [
    { category: 'zakat', amount: 95000, percentage: 33 },
    { category: 'food', amount: 65000, percentage: 23 },
    { category: 'medical', amount: 55000, percentage: 19 },
    { category: 'education', amount: 40000, percentage: 14 },
    { category: 'kafala', amount: 20000, percentage: 7 },
    { category: 'sadaqah', amount: 10000, percentage: 4 },
  ],
};

export const mockNotifications: AppNotification[] = [
  {
    id: 'n1',
    userId: 'u1',
    title: 'Donation Confirmed',
    titleAr: 'تم تأكيد التبرع',
    body: 'Your donation of 500 EGP has been received successfully.',
    bodyAr: 'تم استلام تبرعك بمبلغ 500 ج.م بنجاح.',
    type: 'donation',
    read: false,
    createdAt: '2025-01-20T10:00:00',
  },
  {
    id: 'n2',
    userId: 'u1',
    title: 'Urgent Case',
    titleAr: 'حالة عاجلة',
    body: 'A child needs urgent heart surgery. Can you help?',
    bodyAr: 'طفل يحتاج لعملية قلب عاجلة. هل يمكنك المساعدة؟',
    type: 'urgent',
    read: false,
    createdAt: '2025-01-19T14:00:00',
  },
  {
    id: 'n3',
    userId: 'u1',
    title: 'Volunteer Opportunity',
    titleAr: 'فرصة تطوع',
    body: 'New food distribution event near you. Sign up now!',
    bodyAr: 'حملة توزيع طعام جديدة بالقرب منك. سجّل الآن!',
    type: 'volunteer',
    read: true,
    createdAt: '2025-01-18T09:00:00',
  },
];
